services:
  - type: web
    name: songgen-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 